#!/usr/bin/env node
// Generate src/generated.ts from deployments/abi/*.json (Foundry artifact
// dump, one per contract) + deployments/<chainId>.json (per-chain address
// + tx + deploy block). Output is committed so consumers of the npm
// package don't need Foundry installed, and `pnpm gen` regenerates after
// a fresh `forge build && pnpm abi`.
//
// We emit ABIs inline with `as const` so viem (or other tooling that
// looks at the type-literal) can derive precise read/write argument
// types per function. Hand-writing this file would be ~200KB so we
// generate.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

const CONTRACTS = [
  "WSRX",
  "Multicall3",
  "SentrixSafe",
  "TokenFactory",
  "FactoryToken",
];
const CHAIN_IDS = [7119, 7120];

function readAbi(name) {
  const raw = JSON.parse(
    readFileSync(resolve(ROOT, "deployments/abi", `${name}.json`), "utf8"),
  );
  // Forge artifact has the full object; just need .abi.
  if (!Array.isArray(raw.abi)) {
    throw new Error(`${name}.json missing .abi array`);
  }
  return raw.abi;
}

function readAddresses() {
  const out = {};
  for (const id of CHAIN_IDS) {
    const path = resolve(ROOT, "deployments", `${id}.json`);
    const raw = JSON.parse(readFileSync(path, "utf8"));
    for (const c of CONTRACTS) {
      if (raw[c] && raw[c].address) {
        out[c] ??= {};
        out[c][id] = raw[c].address;
      }
    }
  }
  return out;
}

function emit(name, abi, addressesByChain) {
  const abiLiteral = JSON.stringify(abi, null, 2);
  const addrLines = Object.entries(addressesByChain || {})
    .map(([id, a]) => `    ${id}: "${a}" as \`0x\${string}\`,`)
    .join("\n");
  return `
export const ${name} = {
  abi: ${abiLiteral} as const,
  address: {
${addrLines}
  },
} as const;

export const ${name}_ABI = ${name}.abi;
export type ${name}Address = (typeof ${name}.address)[keyof typeof ${name}.address];
`.trim();
}

function main() {
  const addrMap = readAddresses();
  const blocks = [];
  blocks.push(
    `// AUTO-GENERATED by scripts/gen-types.mjs from deployments/abi/*.json +
// deployments/<chainId>.json. Do not edit by hand — regenerate with
// \`pnpm gen\` after a fresh \`forge build && pnpm abi\`.

/* eslint-disable */`,
  );
  for (const name of CONTRACTS) {
    const abi = readAbi(name);
    blocks.push(emit(name, abi, addrMap[name]));
  }
  // Convenience map keyed by contract name for ad-hoc reflection.
  blocks.push(
    `export const CONTRACTS = {
  WSRX,
  Multicall3,
  SentrixSafe,
  TokenFactory,
  FactoryToken,
} as const;

export const CHAIN_IDS = [7119, 7120] as const;
export type ChainId = (typeof CHAIN_IDS)[number];

/** Look up a contract's deployed address by chain. Throws if the
 * contract has no deployment record on that chain. */
export function getAddress<K extends keyof typeof CONTRACTS>(
  contract: K,
  chainId: ChainId,
): \`0x\${string}\` {
  const a = (CONTRACTS[contract].address as Record<number, \`0x\${string}\`>)[chainId];
  if (!a) {
    throw new Error(
      \`@sentrix-labs/canonical-contracts: \${contract} has no deployment on chain \${chainId}\`,
    );
  }
  return a;
}`,
  );
  const out = blocks.join("\n\n") + "\n";
  writeFileSync(resolve(ROOT, "src/generated.ts"), out);
  console.log(
    `wrote src/generated.ts — ${CONTRACTS.length} contracts × ${CHAIN_IDS.length} chains`,
  );
}

main();
